# Generated by Django 3.1.2 on 2020-11-27 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_início', models.DateTimeField(auto_now_add=True)),
                ('hora_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('data_de_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=125)),
                ('especialidade', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'profissionais',
            },
        ),
        migrations.CreateModel(
            name='Prontuário',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultas', models.ManyToManyField(related_name='consultas', to='core.Consulta')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horário', models.DateTimeField()),
                ('is_disponível', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profissional')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='prontuário',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prontuário'),
        ),
    ]
