# Generated by Django 3.1.2 on 2021-01-20 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=25, null=True)),
                ('função', models.CharField(blank=True, max_length=25, null=True)),
                ('registro', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Célula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('colaboradores', models.ManyToManyField(blank=True, to='core.Colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
            options={
                'verbose_name_plural': 'setores',
            },
        ),
        migrations.CreateModel(
            name='Prontuário',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('célula_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='célula_atual', to='core.célula')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paciente')),
                ('setor_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setor_atual', to='core.setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unidade')),
            ],
        ),
        migrations.CreateModel(
            name='Prescrição',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prescrição', models.DateField()),
                ('prescrição', models.TextField()),
                ('prescritor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescritor', to='core.colaborador')),
                ('prontuário', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prontuário')),
            ],
            options={
                'verbose_name_plural': 'prescrições',
            },
        ),
        migrations.CreateModel(
            name='ExameProcedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='SOLICITADO', max_length=20)),
                ('último_status', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_solicitado', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_resultado', models.DateTimeField(blank=True, null=True)),
                ('prontuário', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prontuário')),
                ('responsável', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsável', to='core.colaborador')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitante', to='core.colaborador')),
            ],
            options={
                'verbose_name': 'exame/procedimento',
                'verbose_name_plural': 'exames/procedimentos',
            },
        ),
        migrations.AddField(
            model_name='célula',
            name='prontuário',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prontuário', to='core.prontuário'),
        ),
        migrations.AddField(
            model_name='célula',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setor'),
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('dados_clínicos', models.TextField()),
                ('célula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.célula')),
                ('prontuário', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prontuário')),
                ('responsável', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.colaborador')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.setor')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
