# Generated by Django 3.1.2 on 2020-11-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuário',
            name='consultas',
            field=models.ManyToManyField(blank=True, related_name='consultas', to='core.Consulta'),
        ),
    ]
