# Generated by Django 3.1.2 on 2020-11-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='local_de_atendimento',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
