# Generated by Django 3.1.2 on 2020-10-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='disponibilidade',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.disponibilidade'),
        ),
    ]
