# Generated by Django 3.1.2 on 2020-10-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201030_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(default='123', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='rg',
            field=models.CharField(default='123', max_length=20),
            preserve_default=False,
        ),
    ]
