# Generated by Django 3.1.2 on 2020-11-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201127_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='caso_clínico',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='observações',
            field=models.TextField(blank=True),
        ),
    ]
