# Generated by Django 3.1.2 on 2020-11-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201127_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='hora_fim',
            new_name='fim',
        ),
        migrations.RenameField(
            model_name='consulta',
            old_name='hora_início',
            new_name='início',
        ),
    ]
