# Generated by Django 3.1.2 on 2020-11-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201127_1121'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Disponibilidade',
            new_name='Agenda',
        ),
    ]
