# Generated by Django 3.1.2 on 2020-11-27 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201127_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='prontuário',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prontuário'),
        ),
    ]
