# Generated by Django 3.1.2 on 2020-11-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agenda_prontuário'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prontuário',
            name='consultas',
        ),
        migrations.AddField(
            model_name='consulta',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profissional'),
        ),
    ]
