# Generated by Django 3.1.2 on 2020-11-28 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201127_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-horário']},
        ),
        migrations.AddField(
            model_name='profissional',
            name='registro',
            field=models.CharField(default='CRM-PI 1202', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consulta',
            name='caso_clínico',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='início',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
