# Generated by Django 3.1.2 on 2020-11-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201128_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='hora_agendamento',
            new_name='hora_confirmação',
        ),
    ]
