# Generated by Django 3.1.2 on 2020-11-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201128_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='telefone',
            field=models.CharField(default='(86) 98131-2488', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='hora_confirmação',
            field=models.DateTimeField(editable=False),
        ),
    ]
