# Generated by Django 3.1.2 on 2020-11-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201128_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='auto_notified',
            field=models.BooleanField(default=False),
        ),
    ]
