# Generated by Django 3.1.2 on 2020-11-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20201129_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_confirmação',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
